### ISSUE TITLE
getUrlParams() in omni-nav-v2.js conflicts with Degrees & Programs back/forward support

### ISSUE THREAD

**Issue by sharissis-brei** [chapmanu/cascade-assets#295] opened 2017-12-07 19:27 UTC
Trello Card: https://trello.com/c/h5jBaODO

It looks like with the new omni nav, a new file called omni-nav-v2.js was added. I found a function in there called getUrlParams() that's throwing an error that makes the D&P page unusable if you take the following steps:

1. Go the the Degrees and Programs page (https://dev-www.chapman.edu/academics/degrees-and-programs.aspx)
2. Select any filters and click the link of a result
3. Browser navigates to the program's detail page
4. Click back button
5. Filtering no longer works because of JS error

This has to do with the URL parameters of D&P being passed into this function and returning a syntax error/unrecognized expression.

All D&P updates are published on Dev Cascade, so you will be able to reproduce it there.

**Comment by tatwell** [comment] 2017-12-07 19:29
Thanks @sharissis-brei. Will address and keep you updated using the issue here.

**Comment by tatwell** [comment] 2017-12-07 21:26
@sharissis-brei Is this the Javascript error you're seeing?

> Uncaught Error: Syntax error, unrecognized expression: [name=type=undergraduate&dap-undergraduate-school=&dap-undergraduate-keyword=]

**Comment by tatwell** [comment] 2017-12-07 21:40
The error can be reproduced locally with this URL:

- http://localhost:5000/omninav_v2#type=undergraduate&dap-undergraduate-school=&dap-undergraduate-keyword=

**Comment by tatwell** [comment] 2017-12-07 21:45
The line of code throwing the error is here:

- https://github.com/chapmanu/cascade-assets/blob/311b57bb49d8ffae202555dff13621b94afc7834/app/assets/javascripts/omni-nav-v2.js#L189

The problem is `nameSelector` has an invalid jQuery selector value, in this case:

    a[name=type=undergraduate&dap-undergraduate-school=&dap-undergraduate-keyword=]

@kaylaziegler: You said that the OmniNav v2 code here was based off the v1 code. The D&P page seemed to work fine with v1. Any idea why it would stop working in v2?

There are some obvious quick and dirty fixes for this, but I'd like to do something that minimizes the chance for unintended side effected.

**Comment by tatwell** [comment] 2017-12-07 21:59
Some tests with jQuery selectors:

```
> s1 = 'a[name=foo]';
> $(s1);
[prevObject: init(1), context: document, selector: "a[name=foo]"]

> s2 = 'a[name=type=foo]';
> $(s2);
jquery.min.js:3 Uncaught Error: Syntax error, unrecognized expression: [name=type=foo]

> s3 = 'a[type=foo]';
> $(s3);

> s4 = 'a[type=foo&bar]';
> $(s4);
Uncaught Error: Syntax error, unrecognized expression: [type=foo&bar]
[prevObject: init(1), context: document, selector: "a[type=foo]"]

> s3 = 'a[type=undergraduate&dap-undergraduate-school=&dap-undergraduate-keyword=]';
> $(s3);
jquery.min.js:3 Uncaught Error: Syntax error, unrecognized expression: [type=undergraduate&dap-undergraduate-school=&dap-undergraduate-keyword=]
```

It seems what we'd want to do is skip the `repositionAnchorsFromUrl` call if it is not a valid jQuery selector here. The selector itself comes from `anchorIdentifier` in this line:

https://github.com/chapmanu/cascade-assets/blob/311b57bb49d8ffae202555dff13621b94afc7834/app/assets/javascripts/omni-nav-v2.js#L182

So if that value is not a valid identifier, use a guard clause (i.e. return).

**Comment by kaylaziegler** [comment] 2017-12-07 22:03
So I wrote that function `repositionForPersonnelAnchor` based on the code in `app/assets/javascripts/global.js`, which parses the URL based on the hash symbol that correlates to the personnel widget. I was unaware that parsing the hash was done with anything other than the personnel widget (relating to the omninav).

Looking at the original code I used to write the part that is giving the error, they do not handle the D&P URL, which means the javascript that was doing it correctly in the past is in some other file that I haven't come across. The javascript I put in `omni_nav_v2.js` was only meant to work with the tab widget, the collapsible regions, and the personnel widget.

**Comment by tatwell** [comment] 2017-12-07 22:07
Thanks, @kaylaziegler.

I realized a simple try/catch block should take care of it:

```
      try {
        var $target = $(nameSelector);
      } catch(error) {
        console.log('repositionAnchorsFromUrl aborted. Invalid selector caught:', nameSelector);
        return false;
      }
```

**Comment by tatwell** [comment] 2017-12-07 22:37
@sharissis-brei I've deployed my patch to Dev Cascade. You should be able to confirm issue resolved here:

- https://dev-www.chapman.edu/academics/degrees-and-programs.aspx#type=undergraduate&dap-undergraduate-school=&dap-undergraduate-keyword=

**Comment by sharissis-brei** [comment] 2017-12-08 14:57
@tatwell Thank you! Looks like this is resolved. I appreciate you looking into it so quickly!

How would you like to handle the PR for this (https://github.com/chapmanu/cascade-assets/pull/238)? Will you be merging your changes into development? My changes should be ready to accept and go live when in tandem with your fix.

**Comment by tatwell** [comment] 2017-12-08 16:26
@sharissis-brei I've merged this patch into master. I've also merged in your PR.

You can proceed with your release. You will need to release assets from Cascade Assets to production, too, to pull in this update:

https://kb-smc.chapman.edu/?p=1894

Please send a free (i.e. not busy) calendar invite to the team (esp Mandy, Ross, and me) to schedule the release to Cascade production.

**Closed by tatwell** 2017-12-08 16:26 UTC
Labels: bug, javascript, trello
