### ISSUE TITLE
Story Feed widget on the 1-column template is not displaying on some pages.

### ISSUE THREAD

**Issue by kaylaziegler** [chapmanu/cascade-assets#218] opened 2017-07-19 22:51 UTC
Trello card: https://trello.com/c/4SsPWtGX/453-urgent-story-feed-widget-on-the-1-column-template-is-not-displaying-on-some-pages

Pull request: https://github.com/chapmanu/inside/pull/848

For some 1-column pages, the Stories widget shows nothing (not pulling blog stories) while for others it works fine.

Screenshots:
<img width="1300" alt="screen_shot_2017-07-11_at_2 12 44_pm" src="https://user-images.githubusercontent.com/11510966/28393100-e41278f6-6c99-11e7-987b-81527642a43d.png">
<img width="1113" alt="screen_shot_2017-07-11_at_2 18 17_pm" src="https://user-images.githubusercontent.com/11510966/28393101-e63f8d3a-6c99-11e7-9311-07ad7a29855d.png">
<img width="1269" alt="screen_shot_2017-07-11_at_2 15 50_pm" src="https://user-images.githubusercontent.com/11510966/28393103-e7e33f56-6c99-11e7-89ed-be647f5e345f.png">
<img width="1109" alt="screen_shot_2017-07-11_at_2 19 03_pm" src="https://user-images.githubusercontent.com/11510966/28393106-e9bd76d4-6c99-11e7-88e8-6e47b595d06e.png">

**Comment by kaylaziegler** [comment] 2017-07-20 15:05
It turns out the feed URL is case sensitive in Cascade. In the screenshot for the broken feed you can see the feed URL in Cascade is Happenings with a capital H. Lowercase h works correctly and shows the happenings blog feed.

I think the reason the featured story is not showing up is because of a `hidden` class that is added to that particular blog post. But I don't know where that's being added or why. If you look at the law feed/featured story that works, it does not have the `hidden` class.

**Comment by tatwell** [comment] 2017-07-20 15:07
@kaylaziegler Can you query that featured story post record from the Blogs database (if you've cloned the data, you can do it locally) and copy result here?

**Comment by kaylaziegler** [comment] 2017-07-20 20:01
Came across Inside issue that looks like the exact same thing: https://github.com/chapmanu/inside/issues/774
PR: https://github.com/chapmanu/cascade-assets/pull/139/files

Confirmed that the [blog post](https://blogs.chapman.edu/happenings/2017/06/26/a-schweitzer-rising-star-takes-action-in-africa/) with `hidden` class in 1-col template that I've been using to test with is also [not showing on Social](https://social.chapman.edu/?service=wordpress).

**Comment by tatwell** [comment] 2017-07-20 20:23
From that issue you found:

> On the issue of the hidden top story (left side of screenshot above), Ross just checked and the post in question had been marked "hide" in Inside on production.

So it's not in Blogs that the post is being hidden (as I was thinking). It's probably in Inside. You, or Ross, might check there.

**Comment by kaylaziegler** [comment] 2017-07-20 20:25
Yes, I was finally able to find the pattern which is that the posts that do not show up have the `hidden: true` attribute in the Inside db.

The question I'm trying to find the answer to is why/how a Wordpress post is marked hidden in the first place.

**Comment by tatwell** [comment] 2017-07-20 20:40
@kaylaziegler Good question. Is it possible an Inside admin marked it so? Check with Ross on how it works.

**Comment by kaylaziegler** [comment] 2017-07-20 20:54
After talking to Michelle, she said that she arranged with James a few years ago that Wordpress posts would automatically be hidden in Social and only be changed when she manually approved them on social.chapman.edu/moderate. The reason is because people like Dodge who publish blog posts usually end up sharing them on Facebook or elsewhere so that it then shows up twice back to back on social.chapman.edu which looked ugly. Posts that have `hidden: true` in Inside are sent to the stories widget on WWW with the `hidden` tag and are automatically not going to be shown.

One solution proposed/agreed upon by Michelle: mark all Wordpress posts as `hidden: false`. She doesn't care.

**Comment by kaylaziegler** [comment] 2017-07-20 20:55
There is one unresolved question: There are some recent "approved" Wordpress posts showing on Social.chapman.edu, but Michelle says she definitely didn't do that, she rarely ever approves them, so it's not clear how exactly they are being filtered in Social.

**Comment by kaylaziegler** [comment] 2017-07-21 18:15
I found an interesting pattern in the Accounts table on Inside. 

FYI: For social media posts like Facebook, the associated Account on Inside is whichever Facebook page posted it, not individuals. For wordpress posts, the associated Account is actually the individual author on Blogs.

In querying the Inside production database, I found that all the wordpress Accounts in our Account table that were `created_at` before January 23 2015 are `cu_affiliated: true`. All wordpress Accounts in the table where `created_at` > January 23 2015, `cu_affiliated: false`. This indicates that there is no actual way to change this value for Wordpress accounts in the table, they will stay that way from the time they are added.

It might take some time now to figure out exactly which commit occurred around the end of January 2015 that caused this, there are some massive merges that happened around then in Inside, and that assumes the breaking change is in fact in Inside.

**Comment by tatwell** [comment] 2017-07-21 18:21
Good sleuthing. Ideally, if this was done in a backend batch operation as it appears, devs created a rake task to do it that could be run from command line and re-run in the future if needed. (It would also be nice if rake task allow a user name argument to passed in to do one user at a time.)

It's unfortunate the why and how was not documented in some discoverable form.

**Comment by kaylaziegler** [comment] 2017-07-21 21:47
So this is one is pretty tricky, due to some limitations with Github's search feature. My conclusion is that the `cu_affiliated` column was added to the Account table in a migration after the initial Account table was made. I think the wordpress accounts (and actually maybe all accounts) that came before the migration were just set to `true`, while the default moving forward was set to `false`. So from then on, any individual who wrote a blog post who was _not already in the Account table_ had `cu_affiliated: false` with no way to change it after creation. That is why there is nothing in the Inside repository (and never has been) that sets the value of `cu_affiliated` unless `service: facebook/instagram/twitter` (because it has a view in /admin).

This is [the migration file](https://github.com/chapmanu/inside/blob/5c3e83d7421523431c7263ae7079da23a10b7678/db/migrate/20140811234418_add_cu_affiliated_to_accounts.rb) that added the `cu_affiliated` column, has since been deleted.

The timeline is not very clear in Github, when tracing this change. Github doesn't search old versions of files, or ones that have been deleted. So it's really difficult to pinpoint where/when exactly this change took effect. But I'm pretty confident that this is the general history of the `cu_affiliated` attribute that led us to where we are now.

For this issue we are going to un-hide all WP posts. The criteria for "hiding" posts is currently `!post.author.cu_affiliated`. So for WP posts this change will render the `cu_affiliated` attribute useless.

**Comment by tatwell** [comment] 2017-07-21 21:55
Yes, it's quite possible that someone just ran a naked mysql query against the production database to update all the accounts or maybe used `wp-cli`. Either way, it would be invisible to history.

Fix works for me. But try to make it transparent in the event product owners don't like the way it works for some reason in future.

**Comment by mandythomas** [comment] 2017-07-24 17:15
@kaylaziegler I am not sure if this is important but will say this in case there's more to fix.. It's about the comment saying the url field in Cascade is case-sensitive. The Data Definition in Cascade simply collects the data (in this case the url). That in itself is neither working or broken. The issue that may still need to be addressed is if the feed url MUST be all lower case then the JQuery that is used to pull in the feed's data and translate it for use on the webpage may need to be tweaked to use a lower-case type of function to transform the url. If you already addressed this somewhere, then ignore.

**Comment by kaylaziegler** [comment] 2017-07-24 17:22
@mandythomas I did discuss this with @tatwell and he said to just tell the product owner to enter the URL in all lowercase instead of having us go in and make a change in the code

**Comment by tatwell** [comment] 2017-07-24 17:53
@kaylaziegler With the example page from the original issue, did you see any browser console errors related to retrieving the feed data?

When I go to https://blogs.chapman.edu/Happenings/ in my browser, I pull it up fine. I didn't realize this worked. It looks like all of the navbar links have the URL as all lowercase. But I can see how a user might reasonably end up at https://blogs.chapman.edu/Happenings, see it works, and paste that into the feed field.

I agree with @mandythomas that it should be fixed. However, I'm not sure simply downcasing the feed URL fully resolves this and I'd like to better understand why the original issue was occurring. 

I think the issue is beyond the scope of this story. I'd like a new story where product owners clarify their expectations.

**Comment by kaylaziegler** [comment] 2017-07-24 18:02
@mandythomas @tatwell There are no errors in the browser console related to retrieving the feed data. I published [this page](https://dev-www.chapman.edu/campus-services/marketing-communication/guidelines-and-resources/web/1-column-modular-example-page.aspx) in dev-cascade that you can look at where the feed has the URL with the capital H.

**Comment by tatwell** [comment] 2017-07-24 18:10
So this is the element in the widget that specifies the feed for the jQuery script:

    <div class="chapman-stories-feed-widget     chapman-stories-feed-widget__medium-bg " data-chapman-stories-button-label="" data-chapman-stories-button-url="" data-chapman-stories-feed-url="https://blogs.chapman.edu/Happenings/" data-chapman-stories-title="Stories Feed Widget" data-chapman-stories-top-story-url="https://blogs.chapman.edu/happenings/2017/06/26/a-schweitzer-rising-star-takes-action-in-africa/">

The relevant attribute:

    data-chapman-stories-feed-url="https://blogs.chapman.edu/Happenings/"

I'll create a new issue and story for this.

**Closed** 2017-07-25 15:57 UTC
Labels: bug, trello
